import type { Metadata } from "next";
import "@/style/globals.css";
import QueryProvider from "@/providers/query_client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </QueryProvider>
  );

}
