package message

const (
	SUCCESS_GET_ME                    = "User profile retrieved successfully."
	SUCCESS_UPDATE_ME                 = "User profile updated successfully."
	SUCCESS_REGISTER                  = "Registration completed successfully."
	SUCCESS_LOGIN                     = "Login successful."
	SUCCESS_LIST_CONVERSATION         = "Conversation retrieved successfully."
	SUCCESS_SEND_FILES                = "Files sent successfully."
	SUCCESS_LOGOUT                    = "Logout successful."
	SUCCESS_LIST_RECENT_CONVERSATION  = "Recent conversation retrieved successfully."
	SUCCESS_GET_MESSAGES              = "Messages retrieved successfully."
	SUCCESS_CREATE_GROUP_CONVERSATION = "Create group conversation successfully."
	SUCCESS_JOIN_GROUP                = "Join group successfully."
	SUCCESS_LEAVE_GROUP               = "Leave group successfully."
	SUCCESS_LIST_MEMBERS_CONVERSATION = "Members retrieved successfully."

	ERR_BIND_REQ                  = "Invalid request payload."
	ERR_GET_ME                    = "Failed to retrieve user profile."
	ERR_UPDATE_ME                 = "Failed to update user profile."
	ERR_REGISTER                  = "Registration failed."
	ERR_LOGIN                     = "Invalid email or password."
	ERR_LIST_CONVERSATION         = "Failed to retrieve conversation."
	ERR_RETRIEVE_FILES            = "Failed to retrieve files."
	ERR_SEND_FILES                = "Failed to send files."
	ERR_LOGOUT                    = "Failed to logout."
	ERR_LIST_RECENT_CONVERSATION  = "Failed to retrieve recent conversation."
	ERR_GET_MESSAGES              = "Failed to retrieve messages."
	ERR_CREATE_GROUP_CONVERSATION = "Failed to create group conversation."
	ERR_JOIN_GROUP                = "Failed to join group."
	ERR_LEAVE_GROUP               = "Failed to leave group."
	ERR_LIST_MEMBERS_CONVERSATION = "Failed to retrieved members."

	WS_SUCCESS_SYNC_CHAT = "Chat synchronized successfully."
	WS_ERR_SYNC_CHAT     = "Failed to synchronize chat."
)
